version: "3.1"

services:
  api:
    image: tracklift-api:latest
    restart: always
    ports:
      - 5000:5000

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: tracklift
